vcart.UI/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace vcart.UI.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

vcart.UI/Areas/User/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using vcart.Services.Interfaces;

namespace vcart.UI.Areas.User.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        IItemService _itemService;
        private IMemoryCache _cache;
        public HomeController(ILogger<HomeController> logger, IItemService itemService, IMemoryCache cache)
        {
            _logger = logger;
            _itemService = itemService;
            _cache = cache;
        }

        public IActionResult Index()
        {
            string key = "catalog";
            var items = _cache.GetOrCreate(key, entry =>
            {
                entry.AbsoluteExpiration = DateTime.Now.AddHours(12);
                entry.SlidingExpiration = TimeSpan.FromMinutes(15);
                return _itemService.GetItems();
            });

            return View(items);
        }
    }
}

vcart.UI/Controllers/HomeController.cs
using vcart.Services.Implementations;
using vcart.Services.Interfaces;
using vcart.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Diagnostics;
using X.PagedList;

namespace vcart.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        IItemService _itemService;
        private IMemoryCache _cache;
        public HomeController(ILogger<HomeController> logger, 
            IItemService itemService, IMemoryCache cache)
        {
            _logger = logger;
            _itemService = itemService;
            _cache = cache;
        }

        public IActionResult Index(int? page)
        {
            //var items = _itemService.GetItems();
            //key
            var pageNumber = page ?? 1;
            string key = "catalog";
            // _cache.Remove(key); // uncomment only if debug the flow
            var items = _cache.GetOrCreate(key, entry =>
            {
                entry.AbsoluteExpiration = DateTime.Now.AddHours(12);
                entry.SlidingExpiration = TimeSpan.FromMinutes(15);
                return _itemService.GetItems();
            });


            //try
            //{
            //    int x = 0, y = 3;
            //    int z = y / x;
            //}
            //catch (Exception ex)
            //{
            //    _logger.LogError(ex, ex.Message);
            //}
            return View(items.ToPagedList(pageNumber,8));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.Any, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

vcart.UI/ViewComponents/ProductMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using vcart.Services.Interfaces;
using X.PagedList;

namespace vcart.UI.ViewComponents
{
    public class ProductMenuViewComponent: ViewComponent
    {
        IItemService _itemService;
        public ProductMenuViewComponent(IItemService itemService)
        {
            _itemService = itemService;
        }

        public IViewComponentResult Invoke(IPagedList productItems)
        {
            //var items = _itemService.GetItems().ToList();
            var items = productItems;
            return View("~/Views/Shared/_ProductMenu.cshtml", items);
        }
    }
}

vcart.UI/Views/Home/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

@model IPagedList<vcart.Models.ItemModel>
@{
    ViewData["Title"] = "Home Page";
}

<div style="background:orange;">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 text-white" style="width:100%">
                <div class="pt-5 pb-5">
                    <h1>V Cart's Online Ordering</h1>
                    <p class="pb-4">
                        Product delivered fast at your door step!
                    </p>
                    <p>
                        <a href="#heading" class="btn btn-success">ORDER ONLINE NOW</a>
                    </p>
                </div>
            </div>
            <div class="col-sm-4 pt-4">
                <img src="~/images/product-header.png" class="img-fluid" />
            </div>
        </div>
    </div>
</div>

@await Component.InvokeAsync("ProductMenu",new { productItems = Model})

@*<div class="row mt-5">
    @foreach (var item in Model)
    {
        <div class="col-sm-4 mb-3">
            <div class="card">
                <img src="@item.ImageUrl" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">@item.Description</p>
                    <a href="javascript:void(0)" onclick="AddToCart('@item.Id', '@item.Name', '@item.UnitPrice', 1)" class="btn btn-primary">Add To Cart</a>
                </div>
            </div>
        </div>
    }
</div>

<div class="toast" id="toastCart">
    <div class="toast-header">
        <strong class="me-auto">Notification</strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body"></div>
</div>*@